FROM centos:7
LABEL Author="aniket khaladkar"

RUN yum install java -y


ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz /opt
RUN tar -xzf /opt/apache-tomcat-8.5.99.tar.gz -C /opt/

# USER root

WORKDIR /opt/apache-tomcat-8.5.99
#RUN chmod +x bin/*.sh
COPY mysql-connector.jar lib/mysql-connector.jar

COPY context.xml conf/context.xml
COPY student.war webapps/student.war

EXPOSE 8080


CMD ["bin/catalina.sh", "run"]
