
FROM amazonlinux:latest


LABEL Author="aniket khaladkar"


RUN yum install java tar gzip -y
WORKDIR /opt


ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz /opt
RUN tar -xzf /opt/apache-tomcat-8.5.99.tar.gz -C /opt/


WORKDIR /opt/apache-tomcat-8.5.99


COPY mysql-connector.jar lib/mysql-connector.jar


COPY context.xml conf/context.xml


COPY student.war webapps/student.war

# Expose port 8080
EXPOSE 8080

# Start Tomcat
CMD ["bin/catalina.sh", "run"]
